name: Apple SwiftUI CI

on:
  push:
    branches: ["main"]
    paths:
      - "apps/apple-swiftui/**"
      - ".github/workflows/swift.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/apple-swiftui/**"
      - ".github/workflows/swift.yml"

jobs:
  build-and-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: apps/apple-swiftui

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
